version: 2

python:
  setup_py_install: true
  install:
    - path: .
      method: pip
      extra_requirements:
        devel
        examples
        all
    - requirements: requirements.txt


# Default
formats: []