version: 2

build:
  tools:
    python: "3.10"

python:
  install:
    - path: .
      method: pip
      extra_requirements: [devel, examples, all]
    - requirements: requirements.txt


# Default
formats: []