name: Tests

on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        backend: ['numpy', 'pytorch']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install git+https://github.com/tensorly/tensorly.git
          python -m pip install torch
          python -m pip install -e .[all,devel]
          python -m pip uninstall condat-tv
          python -m pip install --no-binary :all: condat-tv 
      - name: run tests
        run: python3 -m pytest --cov=matcouply --cov-report=xml
        env:
          TENSORLY_BACKEND: ${{ matrix.backend }}
      - name: upload coverage to Codecov
        if: ${{ matrix.backend == 'numpy' && matrix.os == 'ubuntu-latest'}}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
