name: Tests

on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[all,devel]
      - name: run tests
        run: python3 -m pytest --cov=matcouply --cov-report=xml
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true # optional (default = false)
